### PR TITLE
[UPD]: Updates to support the new Google Form format

### PR DESCRIPTION
**Pull request by pathakshashank17**
The admin has changed the new google form radio button matrix. They have flipped the rows and columns, thus causing the extension to malfunction. This PR fixes that.

Also, I have taken the liberty to publish this extension on the Chrome Web Store. The extension is currently under review, and I will update this PR comment to reflect the status.

### CODE REVIEW

**Comment by TheAnshul756** [comment]
Changes looks good to me. Can you please share a sample form to see the changes in effect.

**Comment by TheAnshul756** [comment]
Also thank you so much for publishing the PR. We created this project during our free time in lockdown and very happy to see our juniors using our extension. :smiley:

**Comment by pathakshashank17** [comment]
This is the currently published OE/HULM choices form (accessible via college email-id): https://forms.gle/wqMHW1BfYjVdmvdJ7
Another sample form (with smaller choices for testing): https://forms.gle/awXhFQBqHSEKM3UY8

**Comment by pathakshashank17** [comment]
**Update**

The updated extension has been published on [Chrome Web Store](https://chrome.google.com/webstore/detail/aiejelpojlfccmpipccpkokpghlbkdnf) and can be installed in one-click.

**Comment by TheAnshul756** [comment]
If you are interested to contribute more to the extension then you can look into these issues:
- #2 
- [Add details of patch 2 and Update the download instructions with chrome web store link](https://github.com/TheAnshul756/hulm-filler/issues/2)

**Pull request merged**
